### ISSUE TITLE
HELP : Want to ask few things about Proot / Linux / Android

### ISSUE THREAD

**Issue by PrashantRawatCoder** [puutaro/CommandClick#14]
Hi ,
I liked your work on proot and Linux in android development. and I am glad that I found you. there are very few developers who are working on this types of projects.

As your Junior, I wanted a help from you. Can you please explain and give me a high level view of how did you managed to run proot , and Linux in Android app. I want to make an open source project which can run few Linux web application on localhost (like phpMyAdmin (I can manage everything else if I am able to run Linux on android) ). I am a complete begginer in android development. But I have some experience in python and web dev.

I would love to help you in your projects too but first I need to learn important skills for that and if I am able to make my project then maybe I will be able to contribut to your project too.

Please help me.

**Comment by puutaro** [comment]
Thank you for your help.  

Right away, about ubuntu and android dvelopment, [userland](https://github.com/CypherpunkArmory/UserLAnd) is suit for you, becuase [userland](https://github.com/CypherpunkArmory/UserLAnd) adopt modern implementation and sophisticated knowhow about linux.  
In fact, while I used [usrland](https://github.com/CypherpunkArmory/UserLAnd) as a reference, intoroduce ubuntu to ComamndClick

(CommandClck itself start [termux](https://github.com/termux/termux-app) client app. In there, I want to have stand alone backend app without [termux](https://github.com/termux/termux-app). 
Threfore, I adopt ubuntu for `CommandClick`.  In that sense, it may be effective for you to create it from a termux client app.)  

Also , require kowhow to build ssh server by docker, becuase ubuntu setup script is shell without interactive.  
Although docker itself don't be used, knowledge to make ssh server by no interractive is must, therefore I feel that it is good to have knowledge of docker.  

In any case, if you first try building an android app or docker container, you may get a sense of it.
