### ISSUE TITLE
Is termux required to use CommandClick?

### ISSUE THREAD

**Issue by GHolk** [puutaro/CommandClick#2]
This app seem great, though I am not sure that did I understand the README.md correctly.
But when I click built-in script (cmdclickButtonExec.js, cmdclick_startup.js and internetButtonExec.js), nothing happen.
Do I have to install the termux to use this app? I did not install it now.

**Comment by GHolk** [comment]
Can you show me some fannels which work without termux?
Installing termux is a large work.

**Comment by puutaro** [comment]
Think you for the question.   
`Fannel` without termux is   

- ctsvViewer  
- siteSammury  
- cmdTwitter(exclude max_tweet_button)  
- selectMenu  
- clipBoardFromatter  
- sentToGmail  
- displayHtmlSource  
- gCurrenderFomartter  
- urlLauncher  

Above you can use without `termux`.    
I first recommend you set `siteSammury` in `homeScriptUrl` in cmdclick_startup.js.   
bellow explain about `homeScriptUrl`   

> specified script, url and html put always bottom in url history    
https://github.com/puutaro/CommandClick#add  

How to  set `siteSammury` in `homeScriptUrl` in `cmdclick_startup.js`  is that long press `cmdclick_startup.js` , and click edit in popup menu. Then, show edit column,  you can found `homeScriptUrl1`, `homeScriptUrl2`, `homeScriptUrl3`... Click `File` button, therefore, open file picker. and select `siteSammury`.   
As a result of, when you long press right buttom button and click  site summary at buttom.  

One thing I can say that `CommandClick` is customize browser. In addition to the `SiteSummary`, above `selectMenu`, `sentToGmail` and `displayHtmlSource` is enforce browser feature.  

Also, `clipBoardFromatter` and `ctsvViewer` is standalone `Fannel`, i.e these have feature like android application.    

I am making `Fannel` on now. for example, one using text to speech,etc.  Hope it suits your use.

**Comment by SoulForeverInPeace** [comment]
I guess I don't understand descriptive english¿

I read your message twice but failed to make a web search.

How do I make a search ?
