### ISSUE TITLE
Bush Translator

### ISSUE THREAD

**Issue by IzzySoft** [puutaro/CommandClick#4]
My checker just alerted me about a non-free library in your app: Bush Translator has no license declared, and thus is not considered FOSS. Apart from that, the use of Google Translate has privacy implications – and also raises the flag for a non-free network. There are several other translation services available, in case you consider switching, e.g. [LibreTranslate](https://github.com/LibreTranslate/LibreTranslate). Meanwhile, I'll have to flag your app with those 2 anti-features.

**Comment by puutaro** [comment]
Thank you for your pointing out. In conclusion, I remove translate feature, becuase of licence problem and no credible(library feature or future).
Also `CommandClick`'s policy is `compact extend`. So, I avoid 1MB over package. With a view to  adding feature concept by small extend, `LibreTranslate` is grey. Prabably, run this server  by termux, make a sense. But, some user avoid even termux application install. Threfore, currently, I'm in the process of contemplating with termux using. But, eventually, by termux, run [LibreTranslate](https://github.com/LibreTranslate/LibreTranslate) or `translate-shell`, becurse `CommandClick` is few `termux client` application also. 
Anyway, I remove no lisence library and if there is anything else in the future, please point it out.

**Comment by IzzySoft** [comment]
Thanks a lot for the fast reaction! When it's gone the license issue of course goes along, so I can remove the anti-features again then (just triggered the update now, so the AFs do not even go online). Checked out, AFs removed – thanks!

Btw: looking at the install instructions, I miss a hint that your app is [available in my repo](https://apt.izzysoft.de/packages/com.puutaro.commandclick/) (if you wish, you could even [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there). [My MR](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12802) to bring it to F-Droid.org seems stuck due to some build problems, so that one could take a little longer…
